import { AuthProvider } from "@/context/AuthContext";
import LayoutContent from "./LayoutContent";
import CategoriesProvider from "@/context/CategoriesContext";
import BlogsProvider from "@/context/BlogContext";
import { getAllCategories } from "@/services/CategorieService";
import { getAllBlogs } from "@/services/BlogService";
import "./globals.css";
import ErrorDisplay from "@/components/shared/ErrorDisplay";

export const metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

async function getInitialData() {
  try {
    const [blogs, categories] = await Promise.all([
      getAllBlogs(),
      getAllCategories(),
    ]);

    return {
      blogs: blogs.success ? blogs.data : [],
      categories: categories.success ? categories.data : [],
      hasError: !blogs.success || !categories.success,
      error: blogs.error || categories.error,
    };
  } catch (error) {
    console.error("Error fetching initial data:", error);
    return {
      blogs: [],
      categories: [],
      hasError: true,
      error: {
        message: "خطا در بارگذاری داده‌ها",
        type: "SERVER_ERROR",
        statusCode: 500,
      },
    };
  }
}

export default async function RootLayout({ children }) {
  const { blogs, categories, hasError, error } = await getInitialData();

  const Providers = ({ children }) => (
    <BlogsProvider blogsData={blogs}>
      <CategoriesProvider categoriesData={categories}>
        {children}
      </CategoriesProvider>
    </BlogsProvider>
  );

  return (
    <html lang="fa" dir="rtl">
      <body className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-gray-100">
        {/* Background Effects */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-600/20 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-pink-600/20 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl"></div>
          <div className="absolute top-1/4 right-1/4 w-64 h-64 bg-blue-600/10 rounded-full blur-3xl"></div>
        </div>

        <AuthProvider>
          {hasError ? (
            <LayoutContent>
              <div className="min-h-screen flex items-center justify-center">
                <ErrorDisplay
                  error={error}
                />
              </div>
            </LayoutContent>
          ) : (
            <Providers>
              <LayoutContent>{children}</LayoutContent>
            </Providers>
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
